name: Github Action for LaTeX
on: [push]
jobs: 
    latex-to-pdf: 
        runs-on: ubuntu-latest
        steps: 
            - name: Setup Git repos
              uses: actions/checkout@v4
            - name: Github Action for LaTeX
              uses: xu-cheng/latex-action@3.1.0
              with: 
                  root_file: |
                      cvtr.tex
                      cv.tex
            - uses: stefanzweifel/git-auto-commit-action@v4
              with: 
                  commit_message: ADd PDF(s).
